language: python
cache:
  directories:
    - $HOME/.cache/pip
    # Add cache for pre-commit on repo that uses it (mandatory for >= 13)
    - $HOME/.cache/pre-commit

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - expect-dev

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "pre-commit"
      python: "3.6" # Black requires python >= 3.6
      install: pip install pre-commit
      script: pre-commit run --all --show-diff-on-failure --verbose --color always
      after_success:
      before_install:
    - stage: test
      env:
        # add MAKEPOT="1" to a TEST line to export .pot files from
        # the test database after test success
        - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB"

env:
  global:
    - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - PHANTOMJS_VERSION="latest"
    - WEBSITE_REPO="1"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
