name: Lint
on: [pull_request, push]

jobs:
  Flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: GitHub Action for Flake8
        uses: cclauss/GitHub-Action-for-Flake8@master
        with:
          args: flake8 . --count --show-source --statistics
