name: Lint
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 2
        uses: actions/setup-python@v1
        if: github.ref == 'refs/heads/10.0'
        with:
          python-version: 2.7
      - name: Setup Python 3
        uses: actions/setup-python@v1
        if: github.ref != 'refs/heads/10.0'
        with:
          python-version: 3.7
      - name: Install flake8
        run: pip install flake8
      - name: Flake8 action
        uses: suo/flake8-github-action@v1
        with:
          checkName: 'flake8'  # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
